apiVersion: apps/v1
kind: Deployment
metadata:
  name: quorum-rabbitmq-perf-test
  labels:
    app.kubernetes.io/name: quorum-rabbitmq-perf-test
    app.kubernetes.io/instance: quorum-rabbitmq-perf-test
    app.kubernetes.io/version: "2.18.0"
    app.kubernetes.io/component: quorum-rabbitmq-perf-test
    app.kubernetes.io/part-of: rabbitmq
    app.kubernetes.io/managed-by: manually
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quorum-rabbitmq-perf-test
  template:
    metadata:
      labels:
        app: quorum-rabbitmq-perf-test
        app.kubernetes.io/name: quorum-rabbitmq-perf-test
        app.kubernetes.io/component: quorum-rabbitmq-perf-test
        app.kubernetes.io/part-of: rabbitmq
    spec:
      containers:
        - name: perftest
          image: pivotalrabbitmq/perf-test:2.18.0
          ports:
            - containerPort: 8080
              name: metrics
          resources:
            limits:
              cpu: 2
              memory: 2G
            requests:
              cpu: 1
              memory: 1G
          command:
            - /bin/bash
            - -c
          args:
            - |-
              bin/runjava com.rabbitmq.perf.PerfTest \
                --uri "amqp://$RABBITMQ_USER:$RABBITMQ_PASS@$RABBITMQ_SERVICE:5672/%2f"
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: RABBITMQ_SERVICE
              value: rabbitmq

            - name: PRODUCER_SCHEDULER_THREADS
              value: "5"
            - name: PRODUCERS
              value: "5"
            - name: PRODUCER_RANDOM_START_DELAY
              value: "10"
            - name: RATE
              value: "10"

            - name: SIZE
              value: "100"

            - name: CONSUMERS_THREAD_POOLS
              value: "10"
            - name: CONSUMERS
              value: "10"

            - name: HEARTBEAT_SENDER_THREADS
              value: "500"
            - name: NIO_THREAD_POOL
              value: "500"

            - name: METRICS_PROMETHEUS
              value: "true"

            - name: CONFIRM
              value: "1"
            - name: FLAG
              value: "persistent"
            - name: JSON_BODY
              value: "true"
            - name: ROUTING_KEY
              value: "quorum"

            - name: QUEUE_PATTERN
              value: "quorum-%d"
            - name: QUEUE_PATTERN_FROM
              value: "1"
            - name: QUEUE_PATTERN_TO
              value: "10"
            - name: QUEUE_ARGS
              value: "x-max-length=1000,x-queue-type=quorum,x-max-in-memory-bytes=10000000"
            - name: AUTO_DELETE
              value: "false"
